### ISSUE TITLE
Nullability support

### ISSUE THREAD

**Issue by AlexBacich** [fluttercommunity/rx_command#47]
Hey, do you have in plans nullability support for the library? I can take care about nullability support for Rx_widgets.

**Comment by escamoteur** [comment]
yep will come, I only have to have time :-)
get_it and functional_listener are already migrated

**Comment by mk-dev-1** [comment]
Morning everyone,

is this coming anytime soon? This library is currently the only one that is left to update our production code.
I've had a go at it myself, but as there are a number of ways to migrate the package, I don't really want to interfere with the intentions of the maintainers...

Thanks for your support!

**Comment by AlexBacich** [comment]
@mk-dev-1 , do you have migrated version? I've run into issues while trying to migrate.

**Comment by escamoteur** [comment]
@josh-ksr have you already done something on this side?

**Comment by escamoteur** [comment]
@mk-dev-1 could you make a PR, so that we could have a look at it?

**Comment by mk-dev-1** [comment]
@escamoteur: Please have a look at #49. I am struggling with an issue, but I am sure it can be resolved rather easily ;-)

**Comment by AlexBacich** [comment]
@escamoteur , would you have time to work on it any time soon? This seems too challenging to me to migrate myself, and this issue is blocking for full project migration to null-safety.

**Comment by escamoteur** [comment]
Will try to do it over the weekend

**Comment by escamoteur** [comment]
ok the weekend wasn't long enough. I'm thinking of making the API exactly (almost) the same as that of flutter_command. This would be a breaking change, though nothing that isn't quickly fixable. What are your thoughts?

**Comment by AlexBacich** [comment]
The whole null-safety is breaking change, so I think now it's the perfect time to introduce it. All logic will be re-tested anyway.

**Comment by escamoteur** [comment]
just pushed first version 6.0.0-null-safety

https://github.com/fluttercommunity/rx_command/tree/null-safety

please have a close look and tell me what you think!

**Comment by mk-dev-1** [comment]
Thank you so much for your work, much appreciated!!

I can see that `initialLastResult` has now become a required field as it is non-nullable. Previously I have not been needing any initial results, therefore I now have to add this for every `RxCommand` that I set up, which seems a bit verbose. From what I can see it is safe to put in a dummy instance of `TResult` as long as I don't use `emitInitialCommandResult`, right?

In any case, maybe there is a way to avoid making `initialLastResult` mandatory?

**Comment by escamoteur** [comment]
Totally right.  This came because for flutter_command it's mandatory as every ValueNotifier needs to have an initial value
Fixed with
6.0.0-null-safety.1

What would be absolutely awesome if someone could update the readme to the changed API, namely:
* `thrownExceptions` now emits `CommandErrors`
* `CommandResult` now contains the param value
* renaming of `canExecute` to `constraint`
also check all source snippets
and if I forgot something else :-)

That would be a great help

**Comment by mk-dev-1** [comment]
Here's another observation / question:

```dart
  static RxCommand<TParam, void> createAsyncNoResult<TParam>(
      AsyncAction1<TParam> action,
      {Stream<bool>? restriction,
      bool emitInitialCommandResult = false,
      bool emitsLastValueToNewSubscriptions = false,
      String? debugName}) {
```
where `AsyncAction1` is defined as

```dart
typedef AsyncAction1<TParam> = Future Function(TParam? param);
```

Should it not be this?

```dart
typedef AsyncAction1<TParam> = Future Function(TParam param);
```
After all, `action` from above is passed to `RxCommandAsync`'s `_func`, which is defined as 

```dart
final Future<TResult> Function(TParam)? _func;
```
... same question for these two:

```dart
typedef Action1<TParam> = void Function(TParam? param);
typedef AsyncFunc1<TParam, TResult> = Future<TResult> Function(TParam? param);
```

Generally, we would not expect a null value to be returned from a command that is set up like `RxCommand.createSync<bool, bool>(_func)`, or am I missing something?

Thanks for your feedback!

**Edit:** Looking at the API of `flutter_command`, this should be corrected to mirror the API of `flutter_command` more closely...

**Comment by escamoteur** [comment]
you are probably right

**Comment by escamoteur** [comment]
could you make a PR and try if it works? I'm kind a busy at the moment

**Comment by 5eeman** [comment]
Hi,
Seems like something broken between migration to null safety. Here is code snippet.
`
var stringCommand = RxCommand.createAsync<String, String>((param) async => 'Here is your string - $param');
stringCommand.listen((value) {
  print('Value is not empty ${value.isNotEmpty}');
});
`
In this case value may be nullable for some reason, while params are non null.

**Comment by mk-dev-1** [comment]
@5eeman This issue has already been identified and is addressed in PR #53

**Comment by mk-dev-1** [comment]
Everything's looking good as far as I can see.

What we are left with is this "issue" here:

Hi all,

I have put together an initial PR for migrating the package to null-safety. However, I can't seem to find a way to migrate the package in a way that this

```dart
late RxCommand<bool, bool> myCommand;

[...]

RxCommand.createSync<bool, bool>(_myFunc)

[...]

bool void _myFunc(bool param) {
return bool;
}

[...]

myCommand();
myCommand.execute();
```

You would expect myCommand() to give you an error, because `TParam` is non-nullable, but it doesn't as `execute` and `call` are set up with a nullable `TParam`:

```dart
  /// Calls the wrapped handler function with an option input parameter
  void execute([TParam? param]);

  /// This makes RxCommand a callable class, so instead of `myCommand.execute()` you can write `myCommand()`
  void call([TParam? param]) => execute(param);
```
I've played around with this, but it seems there is no way to make `TParam` non-nullable and optional at the same time. So we either have to live with this or will have to go for explicitly calling `myCommand(null)` in cases where `TParam` is nullable.

I am okay to live with this. Any thoughts?

**Comment by escamoteur** [comment]
Actually I would call this not a problem but a feature. It took me quite some work to get it work like this so that you don't have to pass null explicitly.
IMHO I prefer that I can still pass the command directly to event handlers in that which is even if this means they might get an exception when I don't pass a parameter for a non nullable.
At least as a design decision that I took for flutter_command

**Comment by escamoteur** [comment]
Thanks a lot for all your help. Migrating a complex package like rx_command isn't easy without people testing and giving feedback!!!

**Comment by mk-dev-1** [comment]
Thanks for the feedback. If it is a design decision that is okay, of course. I just thought I'd ask about it ;-)

**Comment by escamoteur** [comment]
I think we leave the package another week in prerelease mode to see if we get any complaints

**Comment by mk-dev-1** [comment]
I've successfully tested the null-safety release in our app's beta program without experiencing any issues. I'd suggest to go ahead with releasing...

**Comment by escamoteur** [comment]
If we don't get any comments till monday I push a new release version

**Comment by AlexBacich** [comment]
@escamoteur , guess we don't have any comments besides updating docs PR. Please push new version. I'll use it for RxWidgets as well.

**Comment by escamoteur** [comment]
Just pushed V6.0.0
